### ISSUE TITLE
Small improvements and binary vertical navigation

### ISSUE THREAD

**Issue by LauraBMo** [mgrachten/bln-mode#1]
Hello,

I liked a lot your code, really nice idea :100: 
I worked a bit on it, are you ok if I do a "pull request" and we discuss about the changes?

Following your idea, I also created new functions which move the cursor vertically by recursive binary subdivision, maybe it could be nice to add them to your package.

Let me advertise you that that would be my first time with a "pull request" :)

**Comment by mgrachten** [comment]
Hi,

Thanks, I'm glad you enjoy the package! I'm much open to improvements so please make a pull request. Coincidentally (after not having touched the code for more than a year) I made some changes myself last week, that I haven't pushed to github yet. Two changes I have been working on are:

1. Add a binary navigation option where the range is not a single line, but the visible part of the buffer (i.e. the window). From what I understand from your post you are binary-dividing the window (or buffer?) on a line basis. If that's the case the difference between our approaches would be that in the window-wise subdivision I do not take into account linebreaks.

2. Rather than binding "forward" and "backward" movement to two key combinations (e.g. M-j and M-k), have a single key combination for entering the binary navigation mode (e.g. M-c b), and then using single keys (e.g. j and k) to move forward and backward. The advantage of this is that it makes it easy to bind the different types of forward and backward movements (within line, within window, across lines) using different letters.

I will push these changes soon. If you make a pull request we can see if we can merge the code in spite of the divergence (it's just a couple of lines after all).

**Comment by LauraBMo** [comment]
1. Yes, I am binary-dividing the window. What I did is create two new functions. At first call, they move the cursor half window up or down and afterwards they move the cursor up or down the half of the previous jump. In each jump, the cursor is placed at the same column where it was at the first call or at the end of line, if it is not possible.
What do you mean by "I do not take into account linebreaks"? Do you mean that you are considering the hole window as a big line?

2. Do you know the package [https://github.com/abo-abo/hydra](url) 
I think that you are suggesting to define an hydra for the package. It is really useful, many packages incorporate one.

3. Surly you know whether it could be useful or not, but maybe at the end of a journey when the cursors stops the journey could auto-restart if the user keeps calling some `bln-*` command.

**Comment by mgrachten** [comment]
Fixed by https://github.com/mgrachten/bln-mode/pull/3.
